# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"MonteCarloShapley": "monte_carlo_shapley.ipynb",
         "ncr": "sgd_shapley.ipynb",
         "SGDshapley": "sgd_shapley.ipynb",
         "ShapleyValues": "shapley_values.ipynb"}

modules = ["monte_carlo_shapley.py",
           "sgd_shapley.py",
           "shapley_values.py"]

doc_url = "https://simon.grah.github.io/shapkit_nbdev/"

git_url = "https://github.com/simon.grah/shapkit_nbdev/tree/master/"

def custom_doc_links(name): return None
