# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"ShapleyValues": "shapleyvalues.ipynb"}

modules = ["shapleyvalues.py"]

doc_url = "https://simon.grah.github.io/shapkit_nbdev/"

git_url = "https://github.com/simon.grah/shapkit_nbdev/tree/master/"

def custom_doc_links(name): return None
